export interface JobProps{
    id: string;
    title: string;
    description: string;
    location: string;
    country: string;
    state: string;
    city: string;
    jobType: string;
    salary: string;
    skills: string[];
    experienceLevel: string;
    currency: string;
    applicationUrl: string;
    benefits?: string;
    approvaalStatus?: string;
    brokenLink: boolean;
    jobStatus: string;
    responsibilities: string[];
    workSettings: string;
    roleCategory: string;
    qualifications: string[];
    companyLogo?: string;
    companyName?: string;
    ipBlocked: boolean;
    createdAt: string;
    updatedAt: string;
    postedDate: string;
}
