name: Deploy Frontend to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 🧪 Install & build the app on GitHub using your .env
      - name: Build Next.js app
        run: |
          cp .env .env.local    # Next.js reads .env.local during build
          npm ci
          npm run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.EC2_FRONTEND_KEY }}

      - name: Sync files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "mkdir -p ${{ secrets.FRONTEND_DIR }}"
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
            --exclude node_modules --exclude .next/cache --exclude .git \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.FRONTEND_DIR }}

      - name: Install deps & restart app on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.FRONTEND_DIR }}
            npm ci --omit=dev
            pm2 startOrRestart ecosystem.config.js --env production
            pm2 save
          EOF
