name: Deploy Frontend to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.EC2_FRONTEND_KEY }}

      - name: Sync files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p ${{ secrets.FRONTEND_DIR }}"
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
            --exclude node_modules --exclude .next \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.FRONTEND_DIR }}

      - name: Install, build, and restart on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.FRONTEND_DIR }}
            export $(grep -v '^#' .env | xargs)
            npm install --production
            npm run build
            pm2 startOrRestart ecosystem.config.js --env production
            pm2 save
          EOF
