name: Deploy Frontend to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env.production
        run: |
          echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}" > .env.production

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.EC2_FRONTEND_KEY }}

      - name: Deploy to EC2
        run: |
          # ensure target folder exists
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "mkdir -p ${{ secrets.FRONTEND_DIR }}"
          # copy everything except dev/ci artifacts
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
            --exclude node_modules --exclude '.next/cache' --exclude .git \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.FRONTEND_DIR }}

      - name: Install & restart on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.FRONTEND_DIR }}
            npm ci --omit=dev            # install only production deps
            pm2 startOrRestart ecosystem.config.js --env production
            pm2 save
          EOF
